### ISSUE TITLE
Add aka region

### ISSUE THREAD

**Issue by mankoff** [cryo-data/discuss#14]
Each dataset should have an optional region.

```yaml
region: top/sub/name
```

Where `top` can be one of greenland, antarctica, or large area (arctic, himalaya, europe, etc.) or country (norway, switzerland, etc.?
And `sub` can be a sub-region (greenland/southwest, antarctica/thwaites/)

And `name` needs to be a name for the dataset. For other akas, it is easy to pick a name (for example, `author/someone_yyyy` or `organization/GEUS/AWS`. It is a bit trickier to pick a dataset name for each region.

### Optional

Require or suggest a geospatial.{kml,gpkg} for each dataset so we support geospatial search and potentially can contribute to https://journalmap.org/

**Comment by MartinLuethi** [comment]
Sounds good in general. But it is not clear to me, why the hierarchy is indicated with the / character.
In YAML we can give explicit hierarchies, which are parsed automatically, and which can also include several sub-topics.
To expand on your example:

```yaml
region: greenland
    subregion: southwest
         name: KNS
         name: Nordbo
         name: other_cool_glacier
```
Having some geospatial information in the meta file seems to be very important. Here I would require at least one coordinate.

```yaml
position:  -49.32,  69.5
    kml:  optionally the kml filename
    polygon:  optionally a polygon in WKT or similar (SVG) format
```
